#!/bin/bash
aws ec2 run-instances \
--image-id ami-d874e0a0 \
--count 1 \
--instance-type t2.micro  \
--security-group-ids sg-69fbc014 \
--key-name ubuntu1 \
--subnet-id subnet-f4097c93 \
--tag-specifications "ResourceType=instance,Tags=[{Key=name,Value=$1}]"
