---
- name: Install Tomcat
  hosts: ec2
  tasks:
    - name: Install Tomcat
      package: name=tomcat7 state=installed

    - name: Enable and start Tomcat
      service:
        name: tomcat7
        enabled: yes
        state: started

    - name: Download test HelloWorld
      get_url:
        url: https://tomcat.apache.org/tomcat-6.0-doc/appdev/sample/sample.war
        dest: /var/lib/tomcat7/webapps
        mode: 0440
